//
//  SwiftUIView.swift
//  
//
//  Created by Chris Guirguis on 10/6/21.
//

import SwiftUI

public struct LoremIpsumGeneratorHelper {
    public static var text: String { """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Euismod in pellentesque massa placerat duis ultricies lacus sed. Pharetra convallis posuere morbi leo urna molestie at elementum. Quis auctor elit sed vulputate mi sit amet. Urna condimentum mattis pellentesque id nibh tortor id. Et malesuada fames ac turpis. In egestas erat imperdiet sed euismod nisi porta. Imperdiet massa tincidunt nunc pulvinar sapien et. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu. Sodales ut etiam sit amet nisl purus. Purus semper eget duis at tellus. Erat pellentesque adipiscing commodo elit at imperdiet dui accumsan.

At erat pellentesque adipiscing commodo elit at imperdiet dui accumsan. Cras fermentum odio eu feugiat. Nisl suscipit adipiscing bibendum est. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Aliquam nulla facilisi cras fermentum. Aliquam sem fringilla ut morbi tincidunt augue interdum velit. Pellentesque habitant morbi tristique senectus. Sit amet venenatis urna cursus eget nunc scelerisque viverra mauris. Dolor morbi non arcu risus quis varius. Nec tincidunt praesent semper feugiat nibh sed. Vivamus at augue eget arcu dictum varius duis.

Lobortis elementum nibh tellus molestie nunc non blandit massa enim. Vitae nunc sed velit dignissim sodales ut eu sem. Donec ultrices tincidunt arcu non sodales. Maecenas sed enim ut sem viverra aliquet. Arcu ac tortor dignissim convallis aenean et tortor at risus. Mattis molestie a iaculis at erat pellentesque. Lacus vestibulum sed arcu non odio euismod lacinia at quis. Justo nec ultrices dui sapien eget. Mi ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Nibh venenatis cras sed felis.

Praesent tristique magna sit amet purus gravida quis blandit turpis. Id volutpat lacus laoreet non curabitur gravida. At consectetur lorem donec massa. Elementum pulvinar etiam non quam. Sagittis id consectetur purus ut faucibus pulvinar elementum integer enim. Sit amet nisl purus in mollis nunc sed. Vel orci porta non pulvinar neque laoreet suspendisse. Id aliquet lectus proin nibh nisl condimentum id venenatis a. Aliquet bibendum enim facilisis gravida neque. Mattis pellentesque id nibh tortor. Eget magna fermentum iaculis eu non. Proin sed libero enim sed faucibus turpis in eu mi. Nullam vehicula ipsum a arcu cursus vitae congue. Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Feugiat in fermentum posuere urna nec tincidunt praesent semper feugiat. Facilisis leo vel fringilla est. Enim diam vulputate ut pharetra sit amet aliquam id. Tincidunt eget nullam non nisi est sit. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus.

Risus feugiat in ante metus dictum at tempor commodo ullamcorper. Hendrerit dolor magna eget est lorem. Morbi leo urna molestie at elementum eu. Vel facilisis volutpat est velit egestas dui. Vitae auctor eu augue ut lectus arcu. Nisi est sit amet facilisis magna. Diam maecenas sed enim ut sem viverra aliquet eget sit. Donec ultrices tincidunt arcu non sodales neque sodales. Dictum non consectetur a erat. Libero enim sed faucibus turpis in eu mi bibendum neque. Integer quis auctor elit sed. Risus nullam eget felis eget nunc lobortis mattis aliquam. Turpis massa tincidunt dui ut. Ac turpis egestas integer eget aliquet nibh praesent tristique. Vestibulum lorem sed risus ultricies tristique. Morbi quis commodo odio aenean sed. Aliquam nulla facilisi cras fermentum odio.

In hac habitasse platea dictumst. Tortor dignissim convallis aenean et. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et. Nunc pulvinar sapien et ligula ullamcorper malesuada. Sit amet dictum sit amet justo donec enim. Gravida dictum fusce ut placerat orci nulla. Tortor posuere ac ut consequat semper. Eros in cursus turpis massa tincidunt dui ut. Turpis egestas sed tempus urna et pharetra pharetra massa. Imperdiet massa tincidunt nunc pulvinar sapien. Aliquet bibendum enim facilisis gravida. Felis eget nunc lobortis mattis aliquam faucibus purus. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim lobortis. Eget nullam non nisi est sit amet facilisis magna. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. In nibh mauris cursus mattis molestie a iaculis at. Habitant morbi tristique senectus et netus et malesuada fames.

Est placerat in egestas erat imperdiet sed euismod. Non sodales neque sodales ut. Eget magna fermentum iaculis eu non diam phasellus. Dapibus ultrices in iaculis nunc sed augue lacus viverra vitae. Eu consequat ac felis donec et. Viverra mauris in aliquam sem fringilla ut morbi tincidunt augue. Elementum integer enim neque volutpat ac tincidunt vitae semper quis. Nam at lectus urna duis convallis convallis tellus id interdum. Mauris vitae ultricies leo integer malesuada. Purus in massa tempor nec. Neque ornare aenean euismod elementum nisi quis eleifend quam. Varius morbi enim nunc faucibus a pellentesque sit amet. A scelerisque purus semper eget duis at tellus at urna. Turpis tincidunt id aliquet risus. Elit ut aliquam purus sit amet.

Venenatis a condimentum vitae sapien pellentesque habitant morbi. Nec nam aliquam sem et tortor consequat id porta. Amet risus nullam eget felis eget. Donec ac odio tempor orci dapibus ultrices in iaculis. Lectus quam id leo in vitae turpis massa sed. Nisl vel pretium lectus quam id. Nunc scelerisque viverra mauris in aliquam sem fringilla ut. In eu mi bibendum neque egestas congue quisque. Tincidunt arcu non sodales neque sodales ut etiam sit. Ut diam quam nulla porttitor massa id neque aliquam vestibulum. Fames ac turpis egestas integer eget aliquet nibh praesent tristique.

Consequat nisl vel pretium lectus. Lobortis scelerisque fermentum dui faucibus in ornare quam. Nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Tempor commodo ullamcorper a lacus vestibulum sed arcu. Fringilla phasellus faucibus scelerisque eleifend. Eros in cursus turpis massa tincidunt dui ut ornare. Dui faucibus in ornare quam viverra orci sagittis. Rhoncus mattis rhoncus urna neque viverra justo nec ultrices. Turpis massa tincidunt dui ut ornare lectus. Vitae congue mauris rhoncus aenean vel. Auctor elit sed vulputate mi sit amet mauris. Ullamcorper eget nulla facilisi etiam dignissim. Malesuada proin libero nunc consequat interdum. Fermentum posuere urna nec tincidunt praesent semper feugiat. Vestibulum lectus mauris ultrices eros in cursus turpis.

Felis eget nunc lobortis mattis aliquam faucibus purus in. At consectetur lorem donec massa sapien faucibus et molestie ac. Egestas egestas fringilla phasellus faucibus scelerisque. In fermentum et sollicitudin ac orci phasellus egestas. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Sapien eget mi proin sed libero enim sed faucibus turpis. Nulla pellentesque dignissim enim sit amet venenatis urna cursus. Accumsan sit amet nulla facilisi morbi tempus iaculis urna id. Turpis massa sed elementum tempus egestas. Arcu felis bibendum ut tristique et. Urna et pharetra pharetra massa massa ultricies mi quis hendrerit. Pharetra magna ac placerat vestibulum lectus mauris ultrices. Elit sed vulputate mi sit amet mauris commodo quis. Faucibus pulvinar elementum integer enim. Phasellus faucibus scelerisque eleifend donec pretium. Tristique risus nec feugiat in fermentum posuere urna nec. Id interdum velit laoreet id.

Porta non pulvinar neque laoreet suspendisse interdum consectetur. Mauris commodo quis imperdiet massa. Nisl condimentum id venenatis a condimentum vitae. Turpis cursus in hac habitasse platea. Mattis aliquam faucibus purus in massa tempor nec. In nisl nisi scelerisque eu ultrices vitae auctor eu augue. Mattis enim ut tellus elementum sagittis vitae. Ultrices mi tempus imperdiet nulla malesuada pellentesque. Tortor dignissim convallis aenean et tortor. Non nisi est sit amet facilisis magna. Dui accumsan sit amet nulla facilisi morbi tempus iaculis. Lectus quam id leo in vitae turpis massa. Morbi tristique senectus et netus et malesuada fames ac turpis.

Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi tincidunt. Lectus sit amet est placerat in. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin. Sollicitudin tempor id eu nisl. Et sollicitudin ac orci phasellus egestas tellus. Vestibulum mattis ullamcorper velit sed. Cras tincidunt lobortis feugiat vivamus at augue eget arcu. Augue mauris augue neque gravida. Hac habitasse platea dictumst quisque sagittis purus sit. Augue ut lectus arcu bibendum at varius vel pharetra vel. Amet commodo nulla facilisi nullam vehicula ipsum a arcu cursus. Ac placerat vestibulum lectus mauris ultrices eros in. Diam phasellus vestibulum lorem sed risus ultricies tristique. In metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Mauris pellentesque pulvinar pellentesque habitant. Turpis egestas integer eget aliquet nibh praesent tristique magna. Eu tincidunt tortor aliquam nulla facilisi.

Tristique senectus et netus et malesuada fames. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus. Proin sed libero enim sed faucibus turpis. Ac turpis egestas integer eget aliquet nibh praesent tristique. Cursus euismod quis viverra nibh cras pulvinar. Odio pellentesque diam volutpat commodo sed egestas egestas fringilla. In ante metus dictum at tempor commodo. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum integer. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. In dictum non consectetur a erat nam at lectus. Est lorem ipsum dolor sit amet consectetur. Scelerisque varius morbi enim nunc faucibus a pellentesque sit. Porttitor massa id neque aliquam vestibulum morbi blandit cursus. Amet consectetur adipiscing elit duis tristique sollicitudin nibh. Nec dui nunc mattis enim ut tellus elementum sagittis. Sit amet nulla facilisi morbi tempus iaculis. Vitae auctor eu augue ut lectus arcu bibendum at. Consectetur libero id faucibus nisl tincidunt eget nullam non nisi. Donec et odio pellentesque diam volutpat commodo sed egestas. Sed augue lacus viverra vitae congue eu.

In nulla posuere sollicitudin aliquam ultrices sagittis orci. Suspendisse potenti nullam ac tortor vitae. Convallis tellus id interdum velit laoreet id. Vestibulum lorem sed risus ultricies tristique nulla. Id donec ultrices tincidunt arcu. Elementum tempus egestas sed sed risus pretium. Turpis egestas integer eget aliquet nibh praesent. Porta lorem mollis aliquam ut porttitor leo a diam sollicitudin. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Diam maecenas sed enim ut sem viverra aliquet eget. At imperdiet dui accumsan sit.

Et netus et malesuada fames ac turpis egestas. Interdum varius sit amet mattis vulputate enim. Pharetra vel turpis nunc eget lorem dolor sed viverra. Urna condimentum mattis pellentesque id. Et egestas quis ipsum suspendisse ultrices. Aliquam purus sit amet luctus venenatis lectus. Adipiscing diam donec adipiscing tristique risus nec feugiat in. Sagittis orci a scelerisque purus semper. Cras sed felis eget velit aliquet sagittis. Mauris ultrices eros in cursus turpis massa tincidunt dui. In pellentesque massa placerat duis. Id semper risus in hendrerit gravida rutrum quisque non tellus. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Magna ac placerat vestibulum lectus mauris ultrices eros. Volutpat maecenas volutpat blandit aliquam etiam. Eu sem integer vitae justo eget magna fermentum iaculis. Sem fringilla ut morbi tincidunt.

Enim facilisis gravida neque convallis a. Varius duis at consectetur lorem donec massa sapien. Commodo sed egestas egestas fringilla phasellus faucibus. Erat nam at lectus urna duis convallis. Habitasse platea dictumst quisque sagittis purus sit amet. Risus sed vulputate odio ut. Arcu dui vivamus arcu felis bibendum ut tristique. Commodo quis imperdiet massa tincidunt nunc pulvinar. Dui sapien eget mi proin sed libero enim sed faucibus. Ac tortor vitae purus faucibus. Fames ac turpis egestas maecenas pharetra convallis posuere. Dictum sit amet justo donec enim diam vulputate. Sit amet facilisis magna etiam. Enim nunc faucibus a pellentesque. Eu consequat ac felis donec et. Nisl vel pretium lectus quam id leo.

Vitae turpis massa sed elementum. Pulvinar mattis nunc sed blandit libero volutpat. Ullamcorper dignissim cras tincidunt lobortis feugiat. Tincidunt arcu non sodales neque. Ultrices neque ornare aenean euismod elementum nisi quis. Sit amet est placerat in egestas. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Tortor posuere ac ut consequat semper viverra nam libero justo. Lacus viverra vitae congue eu consequat. Nibh tortor id aliquet lectus proin nibh nisl condimentum. Id eu nisl nunc mi ipsum faucibus vitae.

Eu sem integer vitae justo eget magna fermentum iaculis. Ipsum faucibus vitae aliquet nec ullamcorper sit amet. Arcu non odio euismod lacinia at quis risus sed vulputate. Nulla pellentesque dignissim enim sit amet venenatis urna cursus. Facilisis sed odio morbi quis commodo odio aenean sed adipiscing. Ullamcorper a lacus vestibulum sed arcu non odio euismod. At lectus urna duis convallis. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. Nulla pharetra diam sit amet. Sed egestas egestas fringilla phasellus faucibus scelerisque. Tempus iaculis urna id volutpat lacus laoreet. At auctor urna nunc id cursus. Ut tellus elementum sagittis vitae. In est ante in nibh mauris cursus mattis. Tortor at risus viverra adipiscing at in tellus. Tortor posuere ac ut consequat semper. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Fermentum iaculis eu non diam phasellus vestibulum lorem sed.

Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Enim lobortis scelerisque fermentum dui faucibus in. Fusce ut placerat orci nulla. Tristique senectus et netus et malesuada. A arcu cursus vitae congue mauris rhoncus aenean vel elit. Ut pharetra sit amet aliquam id. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in. Ut porttitor leo a diam sollicitudin tempor id eu nisl. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est. Egestas egestas fringilla phasellus faucibus scelerisque eleifend. Sollicitudin tempor id eu nisl nunc. Egestas congue quisque egestas diam in arcu cursus euismod quis. Turpis nunc eget lorem dolor sed viverra ipsum. Bibendum neque egestas congue quisque egestas diam in arcu cursus. Nisl pretium fusce id velit ut tortor pretium viverra. Dolor sit amet consectetur adipiscing elit. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Vitae aliquet nec ullamcorper sit amet risus nullam. Dui nunc mattis enim ut. Cras pulvinar mattis nunc sed blandit.

In fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Rhoncus est pellentesque elit ullamcorper. Lorem dolor sed viverra ipsum nunc aliquet bibendum. Et ultrices neque ornare aenean euismod elementum nisi quis eleifend. Ornare quam viverra orci sagittis. Aliquam sem et tortor consequat. Ut sem viverra aliquet eget sit amet tellus. Sapien et ligula ullamcorper malesuada proin libero nunc consequat interdum. Quis commodo odio aenean sed adipiscing diam. Libero justo laoreet sit amet cursus sit. Tempor nec feugiat nisl pretium fusce id velit ut tortor. Libero volutpat sed cras ornare arcu dui vivamus arcu felis. Vehicula ipsum a arcu cursus vitae congue. Facilisis mauris sit amet massa vitae. Venenatis tellus in metus vulputate eu scelerisque. Turpis egestas pretium aenean pharetra magna ac. Adipiscing at in tellus integer feugiat scelerisque varius. Bibendum neque egestas congue quisque. Ac turpis egestas sed tempus urna et pharetra. Condimentum mattis pellentesque id nibh tortor id aliquet.

A arcu cursus vitae congue mauris. Faucibus in ornare quam viverra orci sagittis. Integer vitae justo eget magna fermentum iaculis eu non. Nibh tellus molestie nunc non blandit massa. Risus nec feugiat in fermentum posuere urna nec tincidunt. Faucibus a pellentesque sit amet porttitor. Euismod nisi porta lorem mollis aliquam ut porttitor. Risus commodo viverra maecenas accumsan. Sed nisi lacus sed viverra tellus in hac. Pretium vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae.

Tortor at auctor urna nunc id. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Vitae elementum curabitur vitae nunc. Massa eget egestas purus viverra accumsan in nisl nisi scelerisque. Amet dictum sit amet justo donec. Enim praesent elementum facilisis leo. Feugiat in ante metus dictum at. Sit amet consectetur adipiscing elit pellentesque habitant morbi tristique. Vivamus arcu felis bibendum ut tristique et egestas. Urna condimentum mattis pellentesque id. Nullam non nisi est sit amet facilisis magna. Vel fringilla est ullamcorper eget. Commodo ullamcorper a lacus vestibulum sed arcu non odio euismod. Amet justo donec enim diam.

Duis at consectetur lorem donec massa sapien faucibus. In hendrerit gravida rutrum quisque non tellus orci. Magna fermentum iaculis eu non diam phasellus vestibulum lorem. Diam vulputate ut pharetra sit amet aliquam. Ipsum suspendisse ultrices gravida dictum fusce. Scelerisque purus semper eget duis at tellus. Porttitor leo a diam sollicitudin tempor id eu nisl nunc. Montes nascetur ridiculus mus mauris vitae ultricies leo integer. Viverra suspendisse potenti nullam ac tortor vitae. Lacinia quis vel eros donec. Lobortis elementum nibh tellus molestie nunc non blandit.

Tempor orci dapibus ultrices in. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Vestibulum sed arcu non odio euismod lacinia at quis. Quis viverra nibh cras pulvinar. Orci a scelerisque purus semper eget duis at tellus. Velit egestas dui id ornare arcu odio ut sem nulla. Cursus vitae congue mauris rhoncus aenean. Volutpat maecenas volutpat blandit aliquam etiam erat. Volutpat diam ut venenatis tellus in metus. Nisl tincidunt eget nullam non nisi. Lobortis scelerisque fermentum dui faucibus in. Consectetur libero id faucibus nisl tincidunt eget nullam. Sem integer vitae justo eget magna fermentum iaculis. Orci phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Erat nam at lectus urna duis convallis convallis tellus. Cursus euismod quis viverra nibh cras pulvinar mattis nunc sed. Dolor morbi non arcu risus quis varius quam. Eros in cursus turpis massa tincidunt dui ut ornare. Egestas dui id ornare arcu odio ut. Tristique senectus et netus et.

Praesent tristique magna sit amet purus. Diam volutpat commodo sed egestas egestas. Mi quis hendrerit dolor magna. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Nibh ipsum consequat nisl vel pretium lectus quam id. Facilisis mauris sit amet massa vitae tortor condimentum lacinia. Turpis egestas integer eget aliquet. A condimentum vitae sapien pellentesque habitant morbi tristique senectus. Tincidunt ornare massa eget egestas purus viverra accumsan in. Diam donec adipiscing tristique risus nec feugiat in fermentum.

Mattis enim ut tellus elementum sagittis vitae et leo. Imperdiet proin fermentum leo vel orci porta. Est pellentesque elit ullamcorper dignissim cras tincidunt lobortis feugiat vivamus. Purus ut faucibus pulvinar elementum integer enim neque volutpat ac. Lorem donec massa sapien faucibus et molestie. Imperdiet massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada. Egestas sed tempus urna et pharetra pharetra massa. Feugiat in ante metus dictum at. Pellentesque adipiscing commodo elit at imperdiet. Ac orci phasellus egestas tellus rutrum tellus. Lacinia at quis risus sed vulputate odio. Tortor aliquam nulla facilisi cras fermentum odio. Ultricies leo integer malesuada nunc vel risus commodo. Urna nunc id cursus metus aliquam eleifend mi in nulla. Mi tempus imperdiet nulla malesuada pellentesque.

In fermentum et sollicitudin ac. At varius vel pharetra vel turpis nunc eget lorem dolor. Risus quis varius quam quisque id diam vel. Curabitur gravida arcu ac tortor dignissim convallis. Tristique risus nec feugiat in. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin. Id porta nibh venenatis cras sed felis. Arcu bibendum at varius vel pharetra vel turpis nunc eget. Lobortis feugiat vivamus at augue. Pellentesque massa placerat duis ultricies lacus sed turpis. Nunc id cursus metus aliquam eleifend.

Dui ut ornare lectus sit amet est placerat. Sed lectus vestibulum mattis ullamcorper velit. Sit amet est placerat in egestas erat imperdiet. Dignissim cras tincidunt lobortis feugiat. Sed faucibus turpis in eu mi bibendum neque egestas congue. Rhoncus mattis rhoncus urna neque. Magna fringilla urna porttitor rhoncus dolor purus. Nibh nisl condimentum id venenatis a. Adipiscing diam donec adipiscing tristique risus. Arcu risus quis varius quam quisque. Tellus cras adipiscing enim eu turpis egestas.

Sed lectus vestibulum mattis ullamcorper velit. Vel facilisis volutpat est velit egestas dui id ornare arcu. Consequat mauris nunc congue nisi vitae. Semper auctor neque vitae tempus quam pellentesque nec nam. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Vulputate dignissim suspendisse in est ante in. Placerat orci nulla pellentesque dignissim enim sit amet venenatis urna. Pharetra magna ac placerat vestibulum. Laoreet non curabitur gravida arcu ac tortor dignissim. Erat pellentesque adipiscing commodo elit at imperdiet dui. Euismod nisi porta lorem mollis aliquam ut porttitor leo a. Tristique senectus et netus et malesuada fames. Quam viverra orci sagittis eu volutpat odio facilisis. Nunc congue nisi vitae suscipit tellus mauris. Ultricies mi quis hendrerit dolor magna eget est lorem ipsum. Neque sodales ut etiam sit amet. Ultrices vitae auctor eu augue ut lectus arcu bibendum at. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla facilisi cras. Sed pulvinar proin gravida hendrerit. Sed augue lacus viverra vitae congue.

Diam ut venenatis tellus in metus. In nulla posuere sollicitudin aliquam ultrices. At consectetur lorem donec massa sapien. Nec sagittis aliquam malesuada bibendum arcu. Cursus risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Velit scelerisque in dictum non consectetur a erat nam at. Sit amet nisl purus in mollis nunc sed id semper. Risus quis varius quam quisque id. Turpis nunc eget lorem dolor sed viverra ipsum nunc. Non odio euismod lacinia at. Cursus mattis molestie a iaculis at. Etiam erat velit scelerisque in dictum.

Id porta nibh venenatis cras sed felis eget velit. Blandit volutpat maecenas volutpat blandit. Leo duis ut diam quam nulla. Sed felis eget velit aliquet sagittis id consectetur purus ut. Faucibus in ornare quam viverra orci sagittis eu volutpat odio. Morbi tristique senectus et netus et. Augue mauris augue neque gravida in. Urna et pharetra pharetra massa massa ultricies mi quis. Dictum non consectetur a erat nam at lectus urna duis. Aenean vel elit scelerisque mauris pellentesque pulvinar pellentesque habitant. Laoreet non curabitur gravida arcu ac tortor.

Tortor id aliquet lectus proin nibh nisl condimentum id. Quis hendrerit dolor magna eget est lorem ipsum dolor. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam. Condimentum vitae sapien pellentesque habitant morbi tristique. Eu feugiat pretium nibh ipsum consequat nisl vel. Mauris sit amet massa vitae tortor condimentum. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Pretium vulputate sapien nec sagittis aliquam. Velit aliquet sagittis id consectetur purus ut faucibus. Pellentesque id nibh tortor id aliquet lectus proin. Tortor aliquam nulla facilisi cras fermentum. Aliquet risus feugiat in ante metus dictum at tempor. Est placerat in egestas erat. Id diam maecenas ultricies mi eget mauris. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Tortor aliquam nulla facilisi cras fermentum odio eu feugiat pretium.

Volutpat blandit aliquam etiam erat velit scelerisque. Elit sed vulputate mi sit amet mauris commodo quis. Vulputate ut pharetra sit amet aliquam id diam maecenas. Pellentesque habitant morbi tristique senectus et. Sagittis purus sit amet volutpat consequat mauris nunc congue nisi. Lorem ipsum dolor sit amet consectetur adipiscing. Ut ornare lectus sit amet est. Non quam lacus suspendisse faucibus interdum posuere. Felis bibendum ut tristique et egestas quis. Sed odio morbi quis commodo odio aenean sed adipiscing diam. Mi in nulla posuere sollicitudin aliquam. Maecenas sed enim ut sem viverra aliquet eget sit amet.

Phasellus vestibulum lorem sed risus ultricies tristique nulla aliquet. Eros in cursus turpis massa tincidunt dui. Nisl suscipit adipiscing bibendum est ultricies integer quis. Egestas quis ipsum suspendisse ultrices gravida dictum. Adipiscing at in tellus integer. Interdum velit laoreet id donec. Gravida rutrum quisque non tellus orci ac auctor. Ante in nibh mauris cursus mattis molestie. Elit duis tristique sollicitudin nibh sit amet. Et magnis dis parturient montes nascetur ridiculus. Egestas sed tempus urna et pharetra. Mi proin sed libero enim. In hac habitasse platea dictumst vestibulum rhoncus est pellentesque elit. Augue eget arcu dictum varius. Suscipit adipiscing bibendum est ultricies integer quis auctor elit sed.

Fringilla urna porttitor rhoncus dolor purus. Pellentesque sit amet porttitor eget dolor morbi non arcu. Nulla facilisi morbi tempus iaculis urna id volutpat. Sodales neque sodales ut etiam sit amet nisl. Commodo ullamcorper a lacus vestibulum sed. Et netus et malesuada fames ac. Semper viverra nam libero justo. Id porta nibh venenatis cras. Aliquet enim tortor at auctor. Sollicitudin ac orci phasellus egestas tellus. Vel facilisis volutpat est velit egestas. Etiam non quam lacus suspendisse faucibus interdum posuere lorem ipsum. Id cursus metus aliquam eleifend mi in nulla posuere. Integer feugiat scelerisque varius morbi enim. Laoreet sit amet cursus sit amet dictum sit amet justo. Vitae suscipit tellus mauris a.

Et pharetra pharetra massa massa ultricies. Id interdum velit laoreet id donec ultrices tincidunt. Id volutpat lacus laoreet non curabitur gravida arcu ac. Nec dui nunc mattis enim. A iaculis at erat pellentesque adipiscing commodo. Cras semper auctor neque vitae tempus quam pellentesque nec nam. Sed turpis tincidunt id aliquet risus. Condimentum vitae sapien pellentesque habitant morbi tristique senectus. Maecenas volutpat blandit aliquam etiam erat velit scelerisque. Nunc sed blandit libero volutpat sed cras ornare arcu. Condimentum vitae sapien pellentesque habitant morbi. Tortor aliquam nulla facilisi cras fermentum odio eu. Bibendum at varius vel pharetra vel turpis nunc. Hendrerit gravida rutrum quisque non tellus orci ac auctor augue. Diam donec adipiscing tristique risus nec feugiat in.

In fermentum et sollicitudin ac. Mollis aliquam ut porttitor leo a diam. Aliquam etiam erat velit scelerisque. Sollicitudin tempor id eu nisl nunc mi ipsum. Maecenas pharetra convallis posuere morbi leo urna. Sit amet volutpat consequat mauris. A diam maecenas sed enim ut sem viverra aliquet eget. Lectus quam id leo in vitae turpis massa. Habitant morbi tristique senectus et netus. Aliquam faucibus purus in massa tempor. Mauris nunc congue nisi vitae suscipit. Justo nec ultrices dui sapien eget. Arcu dictum varius duis at consectetur.

In hendrerit gravida rutrum quisque non tellus orci. Sit amet commodo nulla facilisi nullam vehicula ipsum a. Nibh nisl condimentum id venenatis a. In ornare quam viverra orci sagittis. Sed ullamcorper morbi tincidunt ornare massa eget egestas. Id nibh tortor id aliquet lectus proin. At in tellus integer feugiat scelerisque varius morbi enim. Commodo elit at imperdiet dui. Varius sit amet mattis vulputate enim. Donec massa sapien faucibus et molestie. Sem et tortor consequat id porta nibh. Molestie a iaculis at erat pellentesque adipiscing commodo elit at. Non odio euismod lacinia at quis risus sed vulputate odio. Quis risus sed vulputate odio. Habitant morbi tristique senectus et. Lorem donec massa sapien faucibus et molestie ac feugiat sed. Rhoncus mattis rhoncus urna neque viverra justo. Commodo elit at imperdiet dui accumsan. Commodo viverra maecenas accumsan lacus vel facilisis volutpat est velit. Nisi quis eleifend quam adipiscing vitae proin.

Ac tortor dignissim convallis aenean et tortor at risus viverra. Condimentum mattis pellentesque id nibh tortor. Lobortis scelerisque fermentum dui faucibus in. Porttitor massa id neque aliquam vestibulum morbi. Viverra mauris in aliquam sem fringilla ut morbi tincidunt. Sem et tortor consequat id porta nibh. Arcu vitae elementum curabitur vitae nunc sed velit dignissim sodales. A arcu cursus vitae congue mauris rhoncus aenean. Odio morbi quis commodo odio aenean sed adipiscing diam. Facilisis mauris sit amet massa vitae tortor condimentum lacinia. Turpis tincidunt id aliquet risus feugiat in ante metus dictum. Dolor magna eget est lorem ipsum dolor sit amet. Sed risus ultricies tristique nulla. Fringilla est ullamcorper eget nulla facilisi etiam dignissim diam. Cursus risus at ultrices mi tempus.

Amet consectetur adipiscing elit pellentesque habitant morbi. Convallis tellus id interdum velit laoreet id. Leo vel orci porta non pulvinar neque. Amet cursus sit amet dictum sit amet justo donec. Ullamcorper dignissim cras tincidunt lobortis feugiat. Habitant morbi tristique senectus et. Quisque sagittis purus sit amet volutpat consequat mauris. Et magnis dis parturient montes nascetur ridiculus. Libero id faucibus nisl tincidunt eget nullam non nisi. Sed risus pretium quam vulputate dignissim suspendisse in est. Sed vulputate odio ut enim blandit. Velit scelerisque in dictum non consectetur.

Nibh praesent tristique magna sit amet. Aliquam sem fringilla ut morbi tincidunt augue. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Quam nulla porttitor massa id. Commodo elit at imperdiet dui. Sit amet tellus cras adipiscing enim eu turpis egestas pretium. Fringilla est ullamcorper eget nulla facilisi etiam. Odio ut enim blandit volutpat maecenas volutpat blandit. At lectus urna duis convallis. Scelerisque viverra mauris in aliquam. Leo in vitae turpis massa sed elementum tempus. Eleifend mi in nulla posuere sollicitudin aliquam ultrices. Neque vitae tempus quam pellentesque nec nam aliquam. Quis ipsum suspendisse ultrices gravida dictum fusce ut. Enim facilisis gravida neque convallis a cras. Ut eu sem integer vitae justo eget magna fermentum iaculis. Odio eu feugiat pretium nibh ipsum consequat nisl. Proin nibh nisl condimentum id venenatis. Urna condimentum mattis pellentesque id.

At tempor commodo ullamcorper a lacus vestibulum sed arcu non. Quam nulla porttitor massa id neque aliquam vestibulum morbi. Magna sit amet purus gravida quis. In nulla posuere sollicitudin aliquam ultrices. Congue nisi vitae suscipit tellus mauris a diam maecenas. Facilisi nullam vehicula ipsum a arcu cursus. Sed risus pretium quam vulputate dignissim suspendisse. Lectus sit amet est placerat in egestas erat imperdiet. Vivamus arcu felis bibendum ut tristique et. Ut lectus arcu bibendum at varius vel pharetra.

Quis imperdiet massa tincidunt nunc pulvinar sapien. Placerat vestibulum lectus mauris ultrices. Malesuada nunc vel risus commodo viverra. Scelerisque fermentum dui faucibus in ornare quam. Odio euismod lacinia at quis risus. Vivamus at augue eget arcu dictum. Lorem dolor sed viverra ipsum nunc aliquet bibendum enim. A iaculis at erat pellentesque adipiscing. Cursus metus aliquam eleifend mi in nulla posuere. Dignissim suspendisse in est ante in nibh mauris cursus mattis. Ultrices in iaculis nunc sed augue lacus. Elementum eu facilisis sed odio morbi quis. Mattis rhoncus urna neque viverra justo nec ultrices dui sapien. Tortor aliquam nulla facilisi cras fermentum odio eu. Sed enim ut sem viverra aliquet eget sit amet tellus. Id diam maecenas ultricies mi eget mauris.

Fermentum iaculis eu non diam phasellus vestibulum lorem. Ultrices neque ornare aenean euismod elementum nisi. Ultricies integer quis auctor elit sed vulputate. Semper feugiat nibh sed pulvinar proin gravida. Eget nullam non nisi est sit amet facilisis. Enim nunc faucibus a pellentesque sit. Turpis in eu mi bibendum neque. Ullamcorper morbi tincidunt ornare massa eget. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. Euismod in pellentesque massa placerat. Nisl rhoncus mattis rhoncus urna neque viverra justo nec. Venenatis tellus in metus vulputate eu scelerisque felis imperdiet. Consectetur adipiscing elit duis tristique sollicitudin nibh sit amet commodo. Ultricies tristique nulla aliquet enim tortor. Habitasse platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Augue eget arcu dictum varius duis at consectetur. Feugiat nisl pretium fusce id.

Enim eu turpis egestas pretium aenean pharetra magna. Nunc eget lorem dolor sed viverra ipsum nunc aliquet bibendum. Egestas congue quisque egestas diam in arcu cursus euismod quis. Aliquam vestibulum morbi blandit cursus risus at. Sit amet nisl purus in mollis nunc sed id semper. Nunc mi ipsum faucibus vitae aliquet. Malesuada fames ac turpis egestas maecenas pharetra. Eget aliquet nibh praesent tristique magna. Id velit ut tortor pretium viverra suspendisse. Sem integer vitae justo eget. Tristique senectus et netus et malesuada fames.

Luctus venenatis lectus magna fringilla urna porttitor rhoncus. Maecenas sed enim ut sem viverra aliquet eget sit. Arcu non odio euismod lacinia. Donec et odio pellentesque diam. Quam viverra orci sagittis eu volutpat odio facilisis. Egestas quis ipsum suspendisse ultrices gravida. Vitae tortor condimentum lacinia quis vel eros donec ac. Tempus urna et pharetra pharetra massa massa ultricies mi. Massa sed elementum tempus egestas sed sed risus. A pellentesque sit amet porttitor. Nunc faucibus a pellentesque sit amet porttitor. Amet est placerat in egestas erat imperdiet sed euismod. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc. Tempus egestas sed sed risus pretium quam vulputate. Mi sit amet mauris commodo quis imperdiet massa tincidunt nunc. Mi in nulla posuere sollicitudin aliquam ultrices. Nam libero justo laoreet sit amet. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt. Mauris ultrices eros in cursus turpis. Ut ornare lectus sit amet est placerat in egestas erat.

Id semper risus in hendrerit. Ultrices eros in cursus turpis massa tincidunt dui. Venenatis tellus in metus vulputate. Sed arcu non odio euismod lacinia at quis risus. Accumsan in nisl nisi scelerisque eu ultrices. Nunc sed augue lacus viverra vitae congue. Augue mauris augue neque gravida in fermentum et. A iaculis at erat pellentesque adipiscing commodo elit at. Et molestie ac feugiat sed lectus. Pretium lectus quam id leo in vitae turpis massa sed. Tellus integer feugiat scelerisque varius morbi enim nunc. Pellentesque pulvinar pellentesque habitant morbi tristique senectus et netus et. Egestas integer eget aliquet nibh praesent. Placerat orci nulla pellentesque dignissim enim sit amet venenatis. At lectus urna duis convallis convallis tellus id. Maecenas pharetra convallis posuere morbi leo urna. Scelerisque eu ultrices vitae auctor. Cursus risus at ultrices mi tempus imperdiet nulla malesuada.

Pulvinar etiam non quam lacus suspendisse faucibus interdum posuere. Tristique et egestas quis ipsum suspendisse ultrices gravida dictum. Sed elementum tempus egestas sed sed. Urna porttitor rhoncus dolor purus non enim praesent elementum. Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor. Sit amet nulla facilisi morbi tempus iaculis urna id. Nunc aliquet bibendum enim facilisis. Viverra orci sagittis eu volutpat odio facilisis mauris sit amet. Mattis aliquam faucibus purus in massa tempor nec feugiat. Nunc lobortis mattis aliquam faucibus purus in massa tempor. Quis commodo odio aenean sed adipiscing diam donec adipiscing tristique. Pharetra magna ac placerat vestibulum lectus mauris ultrices. Sit amet justo donec enim diam vulputate ut.

Massa tincidunt nunc pulvinar sapien et ligula ullamcorper. Ac felis donec et odio pellentesque. Accumsan lacus vel facilisis volutpat est. Tortor dignissim convallis aenean et tortor at risus viverra. Diam donec adipiscing tristique risus. Arcu non sodales neque sodales ut etiam. At erat pellentesque adipiscing commodo elit at imperdiet. Tortor id aliquet lectus proin. Sapien nec sagittis aliquam malesuada bibendum arcu. Amet tellus cras adipiscing enim.

Tellus cras adipiscing enim eu. Cras pulvinar mattis nunc sed. Ut porttitor leo a diam sollicitudin tempor id. Ut etiam sit amet nisl purus in mollis nunc. Tellus orci ac auctor augue. Enim eu turpis egestas pretium aenean pharetra magna ac. Massa enim nec dui nunc. Tellus in metus vulputate eu scelerisque. Vestibulum morbi blandit cursus risus at ultrices. Mattis rhoncus urna neque viverra justo nec. Ultrices tincidunt arcu non sodales neque sodales. Purus faucibus ornare suspendisse sed nisi. Dignissim enim sit amet venenatis urna cursus. Mi in nulla posuere sollicitudin aliquam ultrices sagittis orci a. Blandit volutpat maecenas volutpat blandit aliquam. Sed libero enim sed faucibus turpis. Nibh mauris cursus mattis molestie. Quis blandit turpis cursus in hac habitasse platea dictumst quisque. Quam quisque id diam vel quam elementum pulvinar etiam non. Consectetur adipiscing elit duis tristique.
"""
    }
    
    public enum GenerationLength: Int {
        case char50 = 50
        case char100 = 100
        case char500 = 500
        case char1000 = 1000
        case char2000 = 2000
        case char5000 = 5000
        case char10000 = 10000
    }
    public static func generateText(_ characterCount: GenerationLength = .char100) -> String {
        
        return String(text.prefix(characterCount.rawValue))
    }
}
